apiVersion: v1
kind: LimitRange
metadata:
  name: database-limit-range
  namespace: testdemo
spec:
  limits:
  - default:
      memory: 256Mi
      cpu: 150m
    defaultRequest:
      memory: 256Mi
      cpu: 150m
    type: Container