apiVersion: v1
kind: Service
metadata:
  name: mongo-hlservice
  namespace: testdemo
  labels:
    name: mongo
    namespace: database
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo